# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: docker.io/recolic/r267
# have upcxx installed

stages:
  - build
  - test

build:
  stage: build
  script:
    - export PATH="/opt/upcxx/bin/:$PATH"
    - cd hw3 && make
  artifacts:
    paths:
      - hw3/kmer_hash
      - hw3/kv_test
      - hw3/dvector_test
    expire_in: 20 minutes


test_1proc_whole:
  stage: test
  script: 
    - wget https://recolic.net/tmp/tiny.txt
    - timeout 1m hw3/kmer_hash tiny.txt test
    - sha1sum test_0.dat | grep 69af6081642850426f1b545ccf61b704820f5251

test_par_whole:
  stage: test
  script: 
    - export PATH="/opt/upcxx/bin/:$PATH"
    - wget https://recolic.net/tmp/tiny.txt
    - timeout 1m upcxx-run -n 16 hw3/kmer_hash tiny.txt test
    - ls test_15.dat test_0.dat test_9.dat
  
test_component:
  stage: test
  script:
    - export PATH="/opt/upcxx/bin/:$PATH"
    - upcxx-run -n 2 hw3/kv_test
    - upcxx-run -n 2 hw3/dvector_test
